export const initialState = {
  timer: {
    isRunning: false,
    time: 25 * 60, // 25 minutes in seconds
    customTime: 25 * 60,
  },
  points: 0,
  unlockedBackgrounds: ['default'],
  selectedBackground: 'default',
  backgroundColor: '#f8e1e7', // default pastel
  tasks: [], // will now be enhanced
  activeSection: 'timer', // timer, shop, music, tasks
  selectedMusicTrack: null, // { id, name, embedUrl }
  currentTaskId: null,
};

export const ACTIONS = {
  START_TIMER: 'START_TIMER',
  STOP_TIMER: 'STOP_TIMER',
  RESET_TIMER: 'RESET_TIMER',
  UPDATE_TIMER: 'UPDATE_TIMER',
  SET_CUSTOM_TIME: 'SET_CUSTOM_TIME',
  ADD_POINTS: 'ADD_POINTS',
  UNLOCK_BACKGROUND: 'UNLOCK_BACKGROUND',
  SELECT_BACKGROUND: 'SELECT_BACKGROUND',
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  TOGGLE_TASK: 'TOGGLE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  ADD_SUBTASK: 'ADD_SUBTASK',
  TOGGLE_SUBTASK: 'TOGGLE_SUBTASK',
  REMOVE_SUBTASK: 'REMOVE_SUBTASK',
  ADD_TAG: 'ADD_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  SET_TASK_DUE_DATE: 'SET_TASK_DUE_DATE',
  SET_TASK_REMINDER: 'SET_TASK_REMINDER',
  SET_TASK_NOTES: 'SET_TASK_NOTES',
  ADD_ATTACHMENT: 'ADD_ATTACHMENT',
  REMOVE_ATTACHMENT: 'REMOVE_ATTACHMENT',
  INCREMENT_POMODORO_COUNT: 'INCREMENT_POMODORO_COUNT',
  SET_TASK_PRIORITY: 'SET_TASK_PRIORITY',
  SET_ACTIVE_SECTION: 'SET_ACTIVE_SECTION',
  LOAD_FROM_STORAGE: 'LOAD_FROM_STORAGE',
  SET_BACKGROUND_COLOR: 'SET_BACKGROUND_COLOR',
  SET_SELECTED_MUSIC_TRACK: 'SET_SELECTED_MUSIC_TRACK',
  CLEAR_SELECTED_MUSIC_TRACK: 'CLEAR_SELECTED_MUSIC_TRACK',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK',
  CLEAR_CURRENT_TASK: 'CLEAR_CURRENT_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
}; 